-- Query size: 977 GB , Running time: 130 sec, Slot time consumed: 25 min 41 sec , Expected used Date Range: One Month, Data source: BQ

SELECT *
     , CASE
        WHEN rank_change = 'HIGH RISE FROM INACTIVITY' THEN 'Growth Priority - 1'
        WHEN rank_change = 'MID RISE FROM INACTIVITY' THEN 'Growth Priority - 2'
        ELSE 'Growth Priority - 3'
       END AS priority_level
     , CASE
        WHEN rank_change = 'HIGH RISE FROM INACTIVITY' THEN 'Outstanding Growth, consider strategic investment'
        WHEN rank_change = 'MID RISE FROM INACTIVITY' THEN 'High growth, track for potential scaling'
        ELSE 'Moderate growth, showing promising trends'
       END AS Description
     , CASE
        WHEN country IN ('Argentina',
        'Bolivia',
        'Chile',
        'Ecuador',
        'French Guiana',
        'Guyana',
        'Paraguay',
        'Peru',
        'Uruguay',
        'Venezuela') THEN 'Spanish South'
        WHEN country IN ('Anguilla',
        'Antigua and Barbuda',
        'Aruba',
        'Bahamas',
        'Barbados',
        'Belize',
        'Bermuda',
        'Bouvet Island',
        'Canada',
        'Cayman Islands',
        'Costa Rica',
        'Cuba',
        'Curacao',
        'Dominica',
        'Dominican Republic',
        'El Salvador',
        'Falkland Islands',
        'Grenada',
        'Guadeloupe',
        'Guatemala',
        'Haiti',
        'Honduras',
        'Jamaica',
        'Martinique',
        'Mexico',
        'Montserrat',
        'Netherlands Antilles',
        'Nicaragua',
        'Panama',
        'Puerto Rico',
        'Saint Barthelemy',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Martin',
        'Saint Pierre and Miquelon',
        'St. Vincent & Grenadines',
        'Suriname',
        'Trinidad and Tobago',
        'Turks and Caicos Islands',
        'United States',
        'British Virgin Islands',
        'U.S. Virgin Islands',
        'South Georgia & South Sandwich') THEN 'Spanish Central'
        WHEN country IN (
        'American Samoa',
        'Australia',
        'British Indian Ocean Territory',
        'Brunei',
        'Cambodia',
        'China',
        'Christmas Island',
        'Cocos (Keeling) Islands',
        'Cook Islands',
        'Fiji',
        'French Polynesia',
        'French Southern Territories',
        'Guam',
        'Heard Island and McDonald Islands',
        'Hong Kong',
        'Indonesia',
        'Japan',
        'Kiribati',
        'South Korea',
        'North Korea',
        'Laos',
        'Macau SAR China',
        'Malaysia',
        'Marshall Islands',
        'Micronesia',
        'Mongolia',
        'Myanmar (Burma)',
        'Nauru',
        'New Caledonia',
        'New Zealand',
        'Niue',
        'Norfolk Island',
        'Northern Mariana Islands',
        'Palau',
        'Papua New Guinea',
        'Philippines',
        'Pitcairn Islands',
        'Samoa',
        'Singapore',
        'Solomon Islands',
        'Taiwan',
        'Thailand',
        'Timor-Leste',
        'Tokelau',
        'Tonga',
        'Tuvalu',
        'U.S. Outlying Islands',
        'Vanuatu',
        'Vietnam',
        'Wallis and Futuna') THEN 'SEA Team'
        WHEN country IN (
        'Afghanistan',
        'Bangladesh',
        'Bhutan',
        'India',
        'Maldives',
        'Nepal',
        'Pakistan',
        'Sri Lanka'
        ) THEN 'ISC Team'
        WHEN country IN (
          'Botswana',
          'Eswatini',
          'Lesotho',
          'Malawi',
          'Namibia',
          'South Africa',
          'Zambia',
          'Zimbabwe'
        ) THEN 'Southern Afica'
        WHEN country IN (
          'Algeria',
          'Bahrain',
          'Egypt',
          'Iran',
          'Iraq',
          'Jordan',
          'Kuwait',
          'Lebanon',
          'Libya',
          'Mauritania',
          'Morocco',
          'Oman',
          'Palestinian Territories',
          'Qatar',
          'Saudi Arabia',
          'Sudan',
          'Syria',
          'Tunisia',
          'United Arab Emirates',
          'Western Sahara',
          'Yemen'
        ) THEN 'MENA'
        WHEN country IN (
          'Armenia',
          'Azerbaijan',
          'Belarus',
          'Kazakhstan',
          'Kyrgyzstan',
          'Moldova',
          'Russia',
          'Tajikistan',
          'Turkmenistan',
          'Ukraine',
          'Uzbekistan',
          'Austria',
          'Belgium',
          'Bulgaria',
          'Croatia',
          'Cyprus',
          'Czech Republic',
          'Denmark',
          'Estonia',
          'Finland',
          'France',
          'Germany',
          'Greece',
          'Hungary',
          'Ireland',
          'Italy',
          'Latvia',
          'Lithuania',
          'Luxembourg',
          'Malta',
          'Netherlands',
          'Poland',
          'Portugal',
          'Romania',
          'Slovakia',
          'Slovenia',
          'Spain',
          'Sweden',
          'Aland Islands',
          'Albania',
          'Andorra',
          'Alderney',
          'Bosnia and Herzegovina',
          'Faroe Islands',
          'France, Metropolitan',
          'Georgia',
          'Gibraltar',
          'Greenland',
          'Guernsey',
          'Iceland',
          'Isle of Man',
          'Israel',
          'Jersey',
          'Liechtenstein',
          'Macedonia',
          'Monaco',
          'Montenegro',
          'Norway',
          'Saint Helena',
          'San Marino',
          'Serbia',
          'Svalbard and Jan Mayen',
          'Switzerland',
          'Turkey',
          'United Kingdom',
          'Vatican City') THEN 'Europe CIS'
          WHEN country IN (
            'Benin',
            'Burkina Faso',
            'Burundi',
            'Cameroon',
            'Central African Republic',
            'Chad',
            'Comoros',
            'Congo - Brazzaville',
            'Congo - Kinshasa',
            "Cote d'Ivoire",
            'Djibouti',
            'Gabon',
            'Guinea',
            'Madagascar',
            'Mali',
            'Mauritius',
            'Mayotte',
            'Niger',
            'Reunion',
            'Rwanda',
            'Senegal',
            'Seychelles',
            'Togo'
          ) THEN 'Africa (French)'
          WHEN country IN (
            'Angola',
            'Cape Verde',
            'Equatorial Guinea',
            'Guinea-Bissau',
            'Mozambique',
            'Sao Tome and Principe'
          ) THEN 'Africa (Portugese)'
          WHEN country IN (
            'Eritrea',
            'Ethiopia',
            'Kenya',
            'Somalia',
            'Somaliland',
            'South Sudan',
            'Uganda'
          ) THEN 'Eastern Africa'
          WHEN country IN (
            'Gambia',
            'Ghana',
            'Liberia',
            'Nigeria',
            'Siera Leone'
          ) THEN 'Western Africa'
          WHEN country = 'Brazil' THEN 'Brazil'
          WHEN country = 'Colombia' THEN 'Colombia'
         END AS sub_region
  FROM development.affiliate_ranking
 WHERE month1_rank = 'INACTIVE'

UNION ALL

SELECT *
     , CASE
        WHEN CAST(rank_change AS INT64) > 10 THEN 'Growth Priority - 1'
        WHEN CAST(rank_change AS INT64) >= 5 AND CAST(rank_change AS INT64) <= 10 THEN 'Growth Priority - 2'
        WHEN CAST(rank_change AS INT64) >= 2 AND CAST(rank_change AS INT64) <= 4  THEN 'Growth Priority - 3'
        WHEN CAST(rank_change AS INT64) = 1 THEN 'Growth Priority - 4'
        ELSE 'Growth Priority - 5'
       END AS priority_level
     , CASE
        WHEN CAST(rank_change AS INT64) > 10 THEN 'Outstanding Growth, consider strategic investment'
        WHEN CAST(rank_change AS INT64) >= 5 AND CAST(rank_change AS INT64) <= 10 THEN 'High growth, track for potential scaling'
        WHEN CAST(rank_change AS INT64) >= 2 AND CAST(rank_change AS INT64) <= 4 THEN 'Moderate growth, showing promising trends'
        WHEN CAST(rank_change AS INT64) = 1 THEN 'Mild growth'
        ELSE 'Minor growth'
       END AS Description
     , CASE
        WHEN country IN ('Argentina',
        'Bolivia',
        'Chile',
        'Ecuador',
        'French Guiana',
        'Guyana',
        'Paraguay',
        'Peru',
        'Uruguay',
        'Venezuela') THEN 'Spanish South'
        WHEN country IN ('Anguilla',
        'Antigua and Barbuda',
        'Aruba',
        'Bahamas',
        'Barbados',
        'Belize',
        'Bermuda',
        'Bouvet Island',
        'Canada',
        'Cayman Islands',
        'Costa Rica',
        'Cuba',
        'Curacao',
        'Dominica',
        'Dominican Republic',
        'El Salvador',
        'Falkland Islands',
        'Grenada',
        'Guadeloupe',
        'Guatemala',
        'Haiti',
        'Honduras',
        'Jamaica',
        'Martinique',
        'Mexico',
        'Montserrat',
        'Netherlands Antilles',
        'Nicaragua',
        'Panama',
        'Puerto Rico',
        'Saint Barthelemy',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Martin',
        'Saint Pierre and Miquelon',
        'St. Vincent & Grenadines',
        'Suriname',
        'Trinidad and Tobago',
        'Turks and Caicos Islands',
        'United States',
        'British Virgin Islands',
        'U.S. Virgin Islands',
        'South Georgia & South Sandwich') THEN 'Spanish Central'
        WHEN country IN (
        'American Samoa',
        'Australia',
        'British Indian Ocean Territory',
        'Brunei',
        'Cambodia',
        'China',
        'Christmas Island',
        'Cocos (Keeling) Islands',
        'Cook Islands',
        'Fiji',
        'French Polynesia',
        'French Southern Territories',
        'Guam',
        'Heard Island and McDonald Islands',
        'Hong Kong',
        'Indonesia',
        'Japan',
        'Kiribati',
        'South Korea',
        'North Korea',
        'Laos',
        'Macau SAR China',
        'Malaysia',
        'Marshall Islands',
        'Micronesia',
        'Mongolia',
        'Myanmar (Burma)',
        'Nauru',
        'New Caledonia',
        'New Zealand',
        'Niue',
        'Norfolk Island',
        'Northern Mariana Islands',
        'Palau',
        'Papua New Guinea',
        'Philippines',
        'Pitcairn Islands',
        'Samoa',
        'Singapore',
        'Solomon Islands',
        'Taiwan',
        'Thailand',
        'Timor-Leste',
        'Tokelau',
        'Tonga',
        'Tuvalu',
        'U.S. Outlying Islands',
        'Vanuatu',
        'Vietnam',
        'Wallis and Futuna') THEN 'SEA Team'
        WHEN country IN (
        'Afghanistan',
        'Bangladesh',
        'Bhutan',
        'India',
        'Maldives',
        'Nepal',
        'Pakistan',
        'Sri Lanka'
        ) THEN 'ISC Team'
        WHEN country IN (
          'Botswana',
          'Eswatini',
          'Lesotho',
          'Malawi',
          'Namibia',
          'South Africa',
          'Zambia',
          'Zimbabwe'
        ) THEN 'Southern Afica'
        WHEN country IN (
          'Algeria',
          'Bahrain',
          'Egypt',
          'Iran',
          'Iraq',
          'Jordan',
          'Kuwait',
          'Lebanon',
          'Libya',
          'Mauritania',
          'Morocco',
          'Oman',
          'Palestinian Territories',
          'Qatar',
          'Saudi Arabia',
          'Sudan',
          'Syria',
          'Tunisia',
          'United Arab Emirates',
          'Western Sahara',
          'Yemen'
        ) THEN 'MENA'
        WHEN country IN (
          'Armenia',
          'Azerbaijan',
          'Belarus',
          'Kazakhstan',
          'Kyrgyzstan',
          'Moldova',
          'Russia',
          'Tajikistan',
          'Turkmenistan',
          'Ukraine',
          'Uzbekistan',
          'Austria',
          'Belgium',
          'Bulgaria',
          'Croatia',
          'Cyprus',
          'Czech Republic',
          'Denmark',
          'Estonia',
          'Finland',
          'France',
          'Germany',
          'Greece',
          'Hungary',
          'Ireland',
          'Italy',
          'Latvia',
          'Lithuania',
          'Luxembourg',
          'Malta',
          'Netherlands',
          'Poland',
          'Portugal',
          'Romania',
          'Slovakia',
          'Slovenia',
          'Spain',
          'Sweden',
          'Aland Islands',
          'Albania',
          'Andorra',
          'Alderney',
          'Bosnia and Herzegovina',
          'Faroe Islands',
          'France, Metropolitan',
          'Georgia',
          'Gibraltar',
          'Greenland',
          'Guernsey',
          'Iceland',
          'Isle of Man',
          'Israel',
          'Jersey',
          'Liechtenstein',
          'Macedonia',
          'Monaco',
          'Montenegro',
          'Norway',
          'Saint Helena',
          'San Marino',
          'Serbia',
          'Svalbard and Jan Mayen',
          'Switzerland',
          'Turkey',
          'United Kingdom',
          'Vatican City') THEN 'Europe CIS'
          WHEN country IN (
            'Benin',
            'Burkina Faso',
            'Burundi',
            'Cameroon',
            'Central African Republic',
            'Chad',
            'Comoros',
            'Congo - Brazzaville',
            'Congo - Kinshasa',
            "Cote d'Ivoire",
            'Djibouti',
            'Gabon',
            'Guinea',
            'Madagascar',
            'Mali',
            'Mauritius',
            'Mayotte',
            'Niger',
            'Reunion',
            'Rwanda',
            'Senegal',
            'Seychelles',
            'Togo'
          ) THEN 'Africa (French)'
          WHEN country IN (
            'Angola',
            'Cape Verde',
            'Equatorial Guinea',
            'Guinea-Bissau',
            'Mozambique',
            'Sao Tome and Principe'
          ) THEN 'Africa (Portugese)'
          WHEN country IN (
            'Eritrea',
            'Ethiopia',
            'Kenya',
            'Somalia',
            'Somaliland',
            'South Sudan',
            'Uganda'
          ) THEN 'Eastern Africa'
          WHEN country IN (
            'Gambia',
            'Ghana',
            'Liberia',
            'Nigeria',
            'Siera Leone'
          ) THEN 'Western Africa'
          WHEN country = 'Brazil' THEN 'Brazil'
          WHEN country = 'Colombia' THEN 'Colombia'
         END AS sub_region
  FROM development.affiliate_ranking
 WHERE month1_rank <> 'INACTIVE'
   AND month2_rank <> 'INACTIVE'
   AND CAST(rank_change AS INT64) > 0

UNION ALL

SELECT *
     , CASE
        WHEN rank_change = 'HIGH DROP TO INACTIVITY' THEN 'Drop Priority - 1'
        WHEN rank_change = 'MID DROP TO INACTIVITY' THEN 'Drop Priority - 2'
        ELSE 'Drop Priority - 5'
       END AS priority_level
     , CASE
        WHEN rank_change = 'HIGH DROP TO INACTIVITY' THEN 'Critical drop, requires immediate follow-up'
        WHEN rank_change = 'MID DROP TO INACTIVITY' THEN 'Significant drop, high concern'
        ELSE 'Minor drop, keep under observation'
       END AS Description
     , CASE
        WHEN country IN ('Argentina',
        'Bolivia',
        'Chile',
        'Ecuador',
        'French Guiana',
        'Guyana',
        'Paraguay',
        'Peru',
        'Uruguay',
        'Venezuela') THEN 'Spanish South'
        WHEN country IN ('Anguilla',
        'Antigua and Barbuda',
        'Aruba',
        'Bahamas',
        'Barbados',
        'Belize',
        'Bermuda',
        'Bouvet Island',
        'Canada',
        'Cayman Islands',
        'Costa Rica',
        'Cuba',
        'Curacao',
        'Dominica',
        'Dominican Republic',
        'El Salvador',
        'Falkland Islands',
        'Grenada',
        'Guadeloupe',
        'Guatemala',
        'Haiti',
        'Honduras',
        'Jamaica',
        'Martinique',
        'Mexico',
        'Montserrat',
        'Netherlands Antilles',
        'Nicaragua',
        'Panama',
        'Puerto Rico',
        'Saint Barthelemy',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Martin',
        'Saint Pierre and Miquelon',
        'St. Vincent & Grenadines',
        'Suriname',
        'Trinidad and Tobago',
        'Turks and Caicos Islands',
        'United States',
        'British Virgin Islands',
        'U.S. Virgin Islands',
        'South Georgia & South Sandwich') THEN 'Spanish Central'
        WHEN country IN (
        'American Samoa',
        'Australia',
        'British Indian Ocean Territory',
        'Brunei',
        'Cambodia',
        'China',
        'Christmas Island',
        'Cocos (Keeling) Islands',
        'Cook Islands',
        'Fiji',
        'French Polynesia',
        'French Southern Territories',
        'Guam',
        'Heard Island and McDonald Islands',
        'Hong Kong',
        'Indonesia',
        'Japan',
        'Kiribati',
        'South Korea',
        'North Korea',
        'Laos',
        'Macau SAR China',
        'Malaysia',
        'Marshall Islands',
        'Micronesia',
        'Mongolia',
        'Myanmar (Burma)',
        'Nauru',
        'New Caledonia',
        'New Zealand',
        'Niue',
        'Norfolk Island',
        'Northern Mariana Islands',
        'Palau',
        'Papua New Guinea',
        'Philippines',
        'Pitcairn Islands',
        'Samoa',
        'Singapore',
        'Solomon Islands',
        'Taiwan',
        'Thailand',
        'Timor-Leste',
        'Tokelau',
        'Tonga',
        'Tuvalu',
        'U.S. Outlying Islands',
        'Vanuatu',
        'Vietnam',
        'Wallis and Futuna') THEN 'SEA Team'
        WHEN country IN (
        'Afghanistan',
        'Bangladesh',
        'Bhutan',
        'India',
        'Maldives',
        'Nepal',
        'Pakistan',
        'Sri Lanka'
        ) THEN 'ISC Team'
        WHEN country IN (
          'Botswana',
          'Eswatini',
          'Lesotho',
          'Malawi',
          'Namibia',
          'South Africa',
          'Zambia',
          'Zimbabwe'
        ) THEN 'Southern Afica'
        WHEN country IN (
          'Algeria',
          'Bahrain',
          'Egypt',
          'Iran',
          'Iraq',
          'Jordan',
          'Kuwait',
          'Lebanon',
          'Libya',
          'Mauritania',
          'Morocco',
          'Oman',
          'Palestinian Territories',
          'Qatar',
          'Saudi Arabia',
          'Sudan',
          'Syria',
          'Tunisia',
          'United Arab Emirates',
          'Western Sahara',
          'Yemen'
        ) THEN 'MENA'
        WHEN country IN (
          'Armenia',
          'Azerbaijan',
          'Belarus',
          'Kazakhstan',
          'Kyrgyzstan',
          'Moldova',
          'Russia',
          'Tajikistan',
          'Turkmenistan',
          'Ukraine',
          'Uzbekistan',
          'Austria',
          'Belgium',
          'Bulgaria',
          'Croatia',
          'Cyprus',
          'Czech Republic',
          'Denmark',
          'Estonia',
          'Finland',
          'France',
          'Germany',
          'Greece',
          'Hungary',
          'Ireland',
          'Italy',
          'Latvia',
          'Lithuania',
          'Luxembourg',
          'Malta',
          'Netherlands',
          'Poland',
          'Portugal',
          'Romania',
          'Slovakia',
          'Slovenia',
          'Spain',
          'Sweden',
          'Aland Islands',
          'Albania',
          'Andorra',
          'Alderney',
          'Bosnia and Herzegovina',
          'Faroe Islands',
          'France, Metropolitan',
          'Georgia',
          'Gibraltar',
          'Greenland',
          'Guernsey',
          'Iceland',
          'Isle of Man',
          'Israel',
          'Jersey',
          'Liechtenstein',
          'Macedonia',
          'Monaco',
          'Montenegro',
          'Norway',
          'Saint Helena',
          'San Marino',
          'Serbia',
          'Svalbard and Jan Mayen',
          'Switzerland',
          'Turkey',
          'United Kingdom',
          'Vatican City') THEN 'Europe CIS'
          WHEN country IN (
            'Benin',
            'Burkina Faso',
            'Burundi',
            'Cameroon',
            'Central African Republic',
            'Chad',
            'Comoros',
            'Congo - Brazzaville',
            'Congo - Kinshasa',
            "Cote d'Ivoire",
            'Djibouti',
            'Gabon',
            'Guinea',
            'Madagascar',
            'Mali',
            'Mauritius',
            'Mayotte',
            'Niger',
            'Reunion',
            'Rwanda',
            'Senegal',
            'Seychelles',
            'Togo'
          ) THEN 'Africa (French)'
          WHEN country IN (
            'Angola',
            'Cape Verde',
            'Equatorial Guinea',
            'Guinea-Bissau',
            'Mozambique',
            'Sao Tome and Principe'
          ) THEN 'Africa (Portugese)'
          WHEN country IN (
            'Eritrea',
            'Ethiopia',
            'Kenya',
            'Somalia',
            'Somaliland',
            'South Sudan',
            'Uganda'
          ) THEN 'Eastern Africa'
          WHEN country IN (
            'Gambia',
            'Ghana',
            'Liberia',
            'Nigeria',
            'Siera Leone'
          ) THEN 'Western Africa'
          WHEN country = 'Brazil' THEN 'Brazil'
          WHEN country = 'Colombia' THEN 'Colombia'
         END AS sub_region
  FROM development.affiliate_ranking
 WHERE month2_rank = 'INACTIVE'

UNION ALL

SELECT *
     , CASE
        WHEN CAST(rank_change AS INT64) < -10 THEN 'Drop Priority - 1'
        WHEN CAST(rank_change AS INT64) >= -10 AND CAST(rank_change AS INT64) <= -5 THEN 'Drop Priority - 2'
        WHEN (CAST(month1_rank AS INT64) >= 1 AND CAST(month1_rank AS INT64) <= 5 AND CAST(rank_change AS INT64) >= -4 AND CAST(rank_change AS INT64) <= -2) OR (CAST(month1_rank AS INT64) >= 5 AND CAST(month1_rank AS INT64) <= 10 AND CAST(rank_change AS INT64) >= -10 AND CAST(rank_change AS INT64) <= -5) THEN 'Drop Priority - 3'
        WHEN (CAST(month1_rank AS INT64) >= 1 AND CAST(month1_rank AS INT64) <= 5 AND CAST(rank_change AS INT64) = -1) OR (CAST(month1_rank AS INT64) >= 5 AND CAST(month1_rank AS INT64) <= 10 AND CAST(rank_change AS INT64) >= -4 AND CAST(rank_change AS INT64) <= -2) THEN 'Drop Priority - 4'
        ELSE 'Drop Priority - 5'
       END AS priority_level
     , CASE
        WHEN CAST(rank_change AS INT64) < -10 THEN 'Critical drop, requires immediate follow-up'
        WHEN CAST(rank_change AS INT64) >= -10 AND CAST(rank_change AS INT64) <= -5 THEN 'Significant drop, high concern'
        WHEN (CAST(month1_rank AS INT64) >= 1 AND CAST(month1_rank AS INT64) <= 5 AND CAST(rank_change AS INT64) >= -4 AND CAST(rank_change AS INT64) <= -2) OR (CAST(month1_rank AS INT64) >= 5 AND CAST(month1_rank AS INT64) <= 10 AND CAST(rank_change AS INT64) >= -10 AND CAST(rank_change AS INT64) <= -5) THEN 'Moderate drop, should be monitored'
        WHEN (CAST(month1_rank AS INT64) >= 1 AND CAST(month1_rank AS INT64) <= 5 AND CAST(rank_change AS INT64) = -1) OR (CAST(month1_rank AS INT64) >= 5 AND CAST(month1_rank AS INT64) <= 10 AND CAST(rank_change AS INT64) >= -4 AND CAST(rank_change AS INT64) <= -2) THEN 'Mild drop, could indicate early warning signs'
        ELSE 'Minor drop, keep under observation'
       END AS Description
     , CASE
        WHEN country IN ('Argentina',
        'Bolivia',
        'Chile',
        'Ecuador',
        'French Guiana',
        'Guyana',
        'Paraguay',
        'Peru',
        'Uruguay',
        'Venezuela') THEN 'Spanish South'
        WHEN country IN ('Anguilla',
        'Antigua and Barbuda',
        'Aruba',
        'Bahamas',
        'Barbados',
        'Belize',
        'Bermuda',
        'Bouvet Island',
        'Canada',
        'Cayman Islands',
        'Costa Rica',
        'Cuba',
        'Curacao',
        'Dominica',
        'Dominican Republic',
        'El Salvador',
        'Falkland Islands',
        'Grenada',
        'Guadeloupe',
        'Guatemala',
        'Haiti',
        'Honduras',
        'Jamaica',
        'Martinique',
        'Mexico',
        'Montserrat',
        'Netherlands Antilles',
        'Nicaragua',
        'Panama',
        'Puerto Rico',
        'Saint Barthelemy',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Martin',
        'Saint Pierre and Miquelon',
        'St. Vincent & Grenadines',
        'Suriname',
        'Trinidad and Tobago',
        'Turks and Caicos Islands',
        'United States',
        'British Virgin Islands',
        'U.S. Virgin Islands',
        'South Georgia & South Sandwich') THEN 'Spanish Central'
        WHEN country IN (
        'American Samoa',
        'Australia',
        'British Indian Ocean Territory',
        'Brunei',
        'Cambodia',
        'China',
        'Christmas Island',
        'Cocos (Keeling) Islands',
        'Cook Islands',
        'Fiji',
        'French Polynesia',
        'French Southern Territories',
        'Guam',
        'Heard Island and McDonald Islands',
        'Hong Kong',
        'Indonesia',
        'Japan',
        'Kiribati',
        'South Korea',
        'North Korea',
        'Laos',
        'Macau SAR China',
        'Malaysia',
        'Marshall Islands',
        'Micronesia',
        'Mongolia',
        'Myanmar (Burma)',
        'Nauru',
        'New Caledonia',
        'New Zealand',
        'Niue',
        'Norfolk Island',
        'Northern Mariana Islands',
        'Palau',
        'Papua New Guinea',
        'Philippines',
        'Pitcairn Islands',
        'Samoa',
        'Singapore',
        'Solomon Islands',
        'Taiwan',
        'Thailand',
        'Timor-Leste',
        'Tokelau',
        'Tonga',
        'Tuvalu',
        'U.S. Outlying Islands',
        'Vanuatu',
        'Vietnam',
        'Wallis and Futuna') THEN 'SEA Team'
        WHEN country IN (
        'Afghanistan',
        'Bangladesh',
        'Bhutan',
        'India',
        'Maldives',
        'Nepal',
        'Pakistan',
        'Sri Lanka'
        ) THEN 'ISC Team'
        WHEN country IN (
          'Botswana',
          'Eswatini',
          'Lesotho',
          'Malawi',
          'Namibia',
          'South Africa',
          'Zambia',
          'Zimbabwe'
        ) THEN 'Southern Afica'
        WHEN country IN (
          'Algeria',
          'Bahrain',
          'Egypt',
          'Iran',
          'Iraq',
          'Jordan',
          'Kuwait',
          'Lebanon',
          'Libya',
          'Mauritania',
          'Morocco',
          'Oman',
          'Palestinian Territories',
          'Qatar',
          'Saudi Arabia',
          'Sudan',
          'Syria',
          'Tunisia',
          'United Arab Emirates',
          'Western Sahara',
          'Yemen'
        ) THEN 'MENA'
        WHEN country IN (
          'Armenia',
          'Azerbaijan',
          'Belarus',
          'Kazakhstan',
          'Kyrgyzstan',
          'Moldova',
          'Russia',
          'Tajikistan',
          'Turkmenistan',
          'Ukraine',
          'Uzbekistan',
          'Austria',
          'Belgium',
          'Bulgaria',
          'Croatia',
          'Cyprus',
          'Czech Republic',
          'Denmark',
          'Estonia',
          'Finland',
          'France',
          'Germany',
          'Greece',
          'Hungary',
          'Ireland',
          'Italy',
          'Latvia',
          'Lithuania',
          'Luxembourg',
          'Malta',
          'Netherlands',
          'Poland',
          'Portugal',
          'Romania',
          'Slovakia',
          'Slovenia',
          'Spain',
          'Sweden',
          'Aland Islands',
          'Albania',
          'Andorra',
          'Alderney',
          'Bosnia and Herzegovina',
          'Faroe Islands',
          'France, Metropolitan',
          'Georgia',
          'Gibraltar',
          'Greenland',
          'Guernsey',
          'Iceland',
          'Isle of Man',
          'Israel',
          'Jersey',
          'Liechtenstein',
          'Macedonia',
          'Monaco',
          'Montenegro',
          'Norway',
          'Saint Helena',
          'San Marino',
          'Serbia',
          'Svalbard and Jan Mayen',
          'Switzerland',
          'Turkey',
          'United Kingdom',
          'Vatican City') THEN 'Europe CIS'
          WHEN country IN (
            'Benin',
            'Burkina Faso',
            'Burundi',
            'Cameroon',
            'Central African Republic',
            'Chad',
            'Comoros',
            'Congo - Brazzaville',
            'Congo - Kinshasa',
            "Cote d'Ivoire",
            'Djibouti',
            'Gabon',
            'Guinea',
            'Madagascar',
            'Mali',
            'Mauritius',
            'Mayotte',
            'Niger',
            'Reunion',
            'Rwanda',
            'Senegal',
            'Seychelles',
            'Togo'
          ) THEN 'Africa (French)'
          WHEN country IN (
            'Angola',
            'Cape Verde',
            'Equatorial Guinea',
            'Guinea-Bissau',
            'Mozambique',
            'Sao Tome and Principe'
          ) THEN 'Africa (Portugese)'
          WHEN country IN (
            'Eritrea',
            'Ethiopia',
            'Kenya',
            'Somalia',
            'Somaliland',
            'South Sudan',
            'Uganda'
          ) THEN 'Eastern Africa'
          WHEN country IN (
            'Gambia',
            'Ghana',
            'Liberia',
            'Nigeria',
            'Siera Leone'
          ) THEN 'Western Africa'
          WHEN country = 'Brazil' THEN 'Brazil'
          WHEN country = 'Colombia' THEN 'Colombia'
         END AS sub_region
  FROM development.affiliate_ranking
 WHERE month1_rank <> 'INACTIVE'
   AND month2_rank <> 'INACTIVE'
   AND CAST(rank_change AS INT64) < 0
