name: Pull Request Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GCP Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: asia-southeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Create environment file
        run: |
          cat > .env <<EOF
          GOOGLE_PROJECT_ID=deriv-bi-ai-sandbox
          LLM_TOKEN=${{ secrets.LLM_TOKEN }}
          SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }}
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }}
          SUPABASE_EMAIL=${{ secrets.SUPABASE_EMAIL }}
          SUPABASE_PASSWORD=${{ secrets.SUPABASE_PASSWORD }}
          GITHUB_TOKEN=${{ secrets.BI_BOT_TOKEN }}
          GITHUB_REPOSITORY=${{ github.repository }}
          GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}
          EOF
      
      - name: Create GCloud key file
        run: |
          echo '${{ secrets.GCLOUD_SERVICE_KEY }}' > gcloud-key.json
      
      - name: Run review agent and validations in container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /app \
            --env-file .env \
            -e GCLOUD_SERVICE_KEY="$(cat gcloud-key.json)" \
            -e GITHUB_WORKSPACE=/workspace \
            asia-southeast1-docker.pkg.dev/deriv-bi-ai-sandbox/bi-pr-review-test-githubactions-asia-southeast1/bi-pr-review:20250714-103224 \
            bash -c "python core/config_validator.py && python core/supabase_logger.py && python core/review_agent.py"
