name: Pull Request Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    container:
      image: asia-southeast1-docker.pkg.dev/deriv-bi-ai-sandbox/bi-pr-review-test-githubactions-asia-southeast1/bi-pr-review:latest
      credentials:
        username: _json_key
        password: ${{ secrets.GCR_PASSWORD }}
    env:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      GOOGLE_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      LLM_TOKEN: ${{ secrets.LLM_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
      SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
      SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.BI_BOT_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: Check container & tools sanity
        run: |
          echo "whoami: $(whoami)"
          git --version
          cat /etc/*release || true
          ls -l /bin/sh

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gitleaks scan for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.BI_BOT_TOKEN }}

      - name: Setup Google Cloud credentials
        run: |
          echo "$GCLOUD_SERVICE_KEY" | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud --quiet config set project "$GOOGLE_PROJECT_ID"

      - name: Validate configuration and parameters
        run: python core/config_validator.py

      - name: Validate Supabase connection
        run: python core/supabase_logger.py

      - name: Run review agent
        run: python core/review_agent.py
